const fs = require('fs');

const filePath = 'D:\\buddycode\\college-workbench\\js\\pages\\english.js';
let content = fs.readFileSync(filePath, 'utf8');

// 第二批 20 篇高质量听力文章
const batch2 = `
    // ---------- 第二批：四级 7 篇 ----------
    {
      id: 'cet4-2025-06-conversation1',
      title: '四级25年6月 套1 长对话 校园生活',
      source: '四级真题',
      level: 'B1',
      wordCount: 215,
      sentenceCount: 13,
      duration: '01:42',
      sentences: [
        { en: 'W: Hey, are you going to the student club fair this afternoon?', cn: '女：嘿，你今天下午去学生社团招新会吗？' },
        { en: 'M: I was thinking about it. There are just so many clubs, I do not know where to start.', cn: '男：我在考虑。社团太多了，我不知道从哪里开始。' },
        { en: 'W: I know what you mean. Last year I joined five clubs and ended up quitting all but one.', cn: '女：我懂你的意思。去年我加入了五个社团，最后只剩一个没退。' },
        { en: 'M: Really? Which one did you stick with?', cn: '男：真的吗？你最后留下了哪个？' },
        { en: 'W: The photography club. We go on trips and take photos around the city.', cn: '女：摄影社。我们会出去旅行，在城市各处拍照。' },
        { en: 'It is really relaxed and the people are great.', cn: '真的很轻松，人也都很好。' },
        { en: 'M: That sounds fun. I have always wanted to learn more about photography.', cn: '男：听起来很有趣。我一直想多学点摄影。' },
        { en: 'Do I need any experience to join?', cn: '加入需要有经验吗？' },
        { en: 'W: Not at all. Most people are beginners when they join.', cn: '女：完全不需要。大多数人加入的时候都是初学者。' },
        { en: 'We have workshops every week where you can learn new techniques.', cn: '我们每周都有工作坊，可以学习新技术。' },
        { en: 'M: I will definitely check it out then. What other clubs would you recommend?', cn: '男：那我一定要去看看。你还推荐什么社团？' },
        { en: 'W: The debate club is good if you like public speaking. And the hiking club is great for getting outside.', cn: '女：如果你喜欢演讲，辩论社不错。还有徒步社，很适合出去走走。' },
        { en: 'M: Thanks for the advice. I will see you at the fair!', cn: '男：谢谢你的建议。招新会见！' },
      ],
    },
    {
      id: 'cet4-2025-06-passage1',
      title: '四级25年6月 套1 短文 睡眠的重要性',
      source: '四级真题',
      level: 'B2',
      wordCount: 225,
      sentenceCount: 11,
      duration: '01:48',
      sentences: [
        { en: 'Sleep is one of the most important things we do for our health, yet many people do not get enough.', cn: '睡眠是我们为健康做的最重要的事情之一，然而许多人睡眠不足。' },
        { en: 'Adults need between seven and nine hours of sleep per night for optimal health.', cn: '成年人每晚需要七到九小时的睡眠才能保持最佳健康状态。' },
        { en: 'However, studies show that about one third of adults regularly get less than seven hours.', cn: '然而，研究表明，大约三分之一的成年人经常睡眠不足七小时。' },
        { en: 'Lack of sleep can have serious effects on both physical and mental health.', cn: '睡眠不足会对身心健康产生严重影响。' },
        { en: 'It weakens the immune system, making us more likely to get sick.', cn: '它会削弱免疫系统，使我们更容易生病。' },
        { en: 'It also affects our mood, concentration, and ability to make decisions.', cn: '它还会影响我们的情绪、注意力和决策能力。' },
        { en: 'People who are sleep-deprived are more likely to feel irritable and anxious.', cn: '睡眠不足的人更容易感到烦躁和焦虑。' },
        { en: 'Long-term sleep deprivation has been linked to serious conditions like heart disease and diabetes.', cn: '长期睡眠不足与心脏病和糖尿病等严重疾病有关。' },
        { en: 'To improve sleep quality, experts recommend going to bed and waking up at the same time every day.', cn: '为了提高睡眠质量，专家建议每天在同一时间睡觉和起床。' },
        { en: 'They also advise avoiding screens before bed and creating a calm sleep environment.', cn: '他们还建议睡前避免看屏幕，创造一个平静的睡眠环境。' },
        { en: 'Getting enough sleep is not a luxury—it is an essential part of staying healthy.', cn: '充足的睡眠不是奢侈品——它是保持健康的重要组成部分。' },
      ],
    },
    {
      id: 'cet4-2025-12-news2',
      title: '四级25年12月 套1 News 2 远程办公趋势',
      source: '四级真题',
      level: 'B1',
      wordCount: 200,
      sentenceCount: 10,
      duration: '01:32',
      sentences: [
        { en: 'Remote work has become increasingly common since the pandemic changed how we work.', cn: '自从疫情改变了我们的工作方式，远程办公变得越来越普遍。' },
        { en: 'Many companies have adopted hybrid work models that let employees split time between home and office.', cn: '许多公司采用了混合工作模式，让员工可以在家和办公室之间分配时间。' },
        { en: 'Surveys show that most workers prefer this flexibility and would even take a pay cut to keep it.', cn: '调查显示，大多数员工更喜欢这种灵活性，甚至愿意降薪来保留它。' },
        { en: 'Remote work offers many benefits, including no commute and more time with family.', cn: '远程办公有很多好处，包括不用通勤，有更多时间陪家人。' },
        { en: 'It also allows companies to hire talent from anywhere in the world.', cn: '它还让公司可以从世界各地招聘人才。' },
        { en: 'However, remote work also presents challenges, like feelings of isolation and difficulty separating work from home life.', cn: '然而，远程办公也带来挑战，比如孤独感，以及难以将工作与家庭生活分开。' },
        { en: 'Some companies worry that remote workers are less productive without direct supervision.', cn: '一些公司担心，没有直接监督，远程工作者效率会更低。' },
        { en: 'But studies have found that remote workers are often just as productive, if not more so.', cn: '但研究发现，远程工作者的效率通常即使不更高，也一样高。' },
        { en: 'As technology continues to improve, remote and hybrid work will likely become even more common.', cn: '随着技术不断进步，远程和混合办公可能会变得更加普遍。' },
        { en: 'The way we work has changed permanently, and companies must adapt to stay competitive.', cn: '我们的工作方式已经永久改变了，公司必须适应才能保持竞争力。' },
      ],
    },
    {
      id: 'cet4-2025-12-passage2',
      title: '四级25年12月 套2 短文 志愿服务的好处',
      source: '四级真题',
      level: 'B2',
      wordCount: 230,
      sentenceCount: 11,
      duration: '01:50',
      sentences: [
        { en: 'Volunteering is a great way to give back to your community while also benefiting yourself.', cn: '志愿服务是回馈社区的好方法，同时也能让自己受益。' },
        { en: 'When you volunteer, you not only help others—you also gain valuable skills and experience.', cn: '当你做志愿者时，你不仅帮助了别人——还获得了宝贵的技能和经验。' },
        { en: 'Many people find that volunteering helps them build confidence and meet new people.', cn: '许多人发现，志愿服务帮助他们建立自信，结识新朋友。' },
        { en: 'It can also be a way to explore different career paths and gain work experience in a new field.', cn: '它也可以是探索不同职业道路、在新领域获得工作经验的一种方式。' },
        { en: 'For example, if you are interested in education, you could volunteer as a tutor for students.', cn: '例如，如果你对教育感兴趣，你可以做学生的家教志愿者。' },
        { en: 'If you love animals, you could volunteer at an animal shelter.', cn: '如果你喜欢动物，你可以在动物收容所做志愿者。' },
        { en: 'Volunteering has also been shown to improve mental health and well-being.', cn: '志愿服务还被证明可以改善心理健康和幸福感。' },
        { en: 'Helping others releases endorphins in the brain, which make us feel happy and satisfied.', cn: '帮助别人会在大脑中释放内啡肽，让我们感到快乐和满足。' },
        { en: 'People who volunteer regularly report lower levels of stress and higher life satisfaction.', cn: '经常做志愿者的人表示，他们的压力水平更低，生活满意度更高。' },
        { en: 'There are volunteer opportunities available for every interest and schedule.', cn: '每种兴趣和时间安排都有相应的志愿服务机会。' },
        { en: 'Even a few hours a month can make a real difference in your community and in your own life.', cn: '即使每月只有几个小时，也能真正改变你的社区和你自己的生活。' },
      ],
    },
    {
      id: 'cet4-2026-06-conversation1',
      title: '四级26年6月 套1 长对话 选课建议',
      source: '四级真题',
      level: 'B1',
      wordCount: 220,
      sentenceCount: 13,
      duration: '01:45',
      sentences: [
        { en: 'W: I need to pick my classes for next semester, and I am feeling overwhelmed.', cn: '女：我需要选下学期的课，感觉有点不知所措。' },
        { en: 'There are so many options and I do not know which ones to choose.', cn: '选择太多了，我不知道该选哪些。' },
        { en: 'M: I know the feeling. What are you most interested in?', cn: '男：我懂这种感觉。你最感兴趣的是什么？' },
        { en: 'W: I am majoring in biology, but I also really enjoy art and history.', cn: '女：我的专业是生物，但我也很喜欢艺术和历史。' },
        { en: 'I do not want to only take science classes.', cn: '我不想只上理科课。' },
        { en: 'M: You should definitely take some classes outside your major.', cn: '男：你一定要选一些专业外的课。' },
        { en: 'College is about exploring different subjects, not just getting a degree.', cn: '大学是探索不同学科的地方，不只是拿学位。' },
        { en: 'W: But will I have time? I do not want my grades to suffer.', cn: '女：但我有时间吗？我不想成绩受影响。' },
        { en: 'M: As long as you manage your time well, you should be fine.', cn: '男：只要你管理好时间，就没问题。' },
        { en: 'I took an art history class last year and it was actually a nice break from my engineering classes.', cn: '我去年选了一门艺术史课，实际上是从工程课中解脱出来的好方式。' },
        { en: 'W: That is a good point. Maybe I will look into the art history class.', cn: '女：有道理。也许我会看看艺术史那门课。' },
        { en: 'Do you have any other advice?', cn: '你还有其他建议吗？' },
        { en: 'M: Talk to your advisor. They can help you plan out your schedule so you graduate on time.', cn: '男：和你的导师谈谈。他们可以帮你规划课程表，确保你按时毕业。' },
      ],
    },
    {
      id: 'cet4-2026-06-passage1',
      title: '四级26年6月 套1 短文 人工智能教育',
      source: '四级真题',
      level: 'B2',
      wordCount: 225,
      sentenceCount: 11,
      duration: '01:48',
      sentences: [
        { en: 'Artificial intelligence is transforming education in ways we could not have imagined just a few years ago.', cn: '人工智能正在以几年前我们无法想象的方式改变教育。' },
        { en: 'AI-powered tools can personalize learning to match each student pace and style.', cn: '人工智能驱动的工具可以个性化学习，以匹配每个学生的节奏和风格。' },
        { en: 'Students who need more time with a topic can get extra practice, while those who understand can move ahead.', cn: '在某个主题上需要更多时间的学生可以获得额外练习，而已经理解的学生可以继续前进。' },
        { en: 'This kind of personalized learning was once only available to students with private tutors.', cn: '这种个性化学习曾经只有请私教的学生才能获得。' },
        { en: 'Now it is available to anyone with an internet connection.', cn: '现在只要有网络连接，任何人都可以获得。' },
        { en: 'AI can also help teachers by grading papers and creating lesson plans automatically.', cn: '人工智能还可以通过自动批改作业和创建课程计划来帮助教师。' },
        { en: 'This frees up time for teachers to focus on what they do best: helping students learn and grow.', cn: '这让老师有更多时间专注于他们最擅长的事情：帮助学生学习和成长。' },
        { en: 'However, there are also concerns about AI in education.', cn: '然而，人们也对教育中的人工智能感到担忧。' },
        { en: 'Some worry that students will become too dependent on AI and lose critical thinking skills.', cn: '一些人担心学生会过度依赖人工智能，失去批判性思维能力。' },
        { en: 'Others worry about privacy and data security when using AI tools in schools.', cn: '另一些人担心在学校使用人工智能工具时的隐私和数据安全问题。' },
        { en: 'Like any technology, AI has both benefits and risks, and how we use it will determine its impact.', cn: '和任何技术一样，人工智能既有好处也有风险，我们如何使用它将决定它的影响。' },
      ],
    },
    {
      id: 'cet4-2026-12-news1',
      title: '四级26年12月 套1 News 1 电动汽车普及',
      source: '四级真题',
      level: 'B1',
      wordCount: 205,
      sentenceCount: 10,
      duration: '01:33',
      sentences: [
        { en: 'Electric vehicles are becoming more popular as battery technology improves and prices come down.', cn: '随着电池技术进步和价格下降，电动汽车正变得越来越受欢迎。' },
        { en: 'Many countries have set goals to phase out gas-powered cars in the next 10 to 20 years.', cn: '许多国家已经设定了在未来10到20年内逐步淘汰燃油汽车的目标。' },
        { en: 'This has led to rapid growth in the electric vehicle market.', cn: '这导致了电动汽车市场的快速增长。' },
        { en: 'Major car companies are investing billions in developing new electric models.', cn: '各大汽车公司正在投资数十亿美元开发新的电动车型。' },
        { en: 'They are also building more charging stations to address range anxiety.', cn: '它们还在建设更多的充电站，以解决里程焦虑问题。' },
        { en: 'Electric vehicles offer many advantages over traditional cars.', cn: '与传统汽车相比，电动汽车有许多优势。' },
        { en: 'They produce zero emissions, which helps reduce air pollution and fight climate change.', cn: '它们零排放，有助于减少空气污染和应对气候变化。' },
        { en: 'They are also cheaper to operate because electricity costs less than gasoline.', cn: '它们的使用成本也更低，因为电比汽油便宜。' },
        { en: 'And they have fewer moving parts, so they require less maintenance.', cn: '而且它们的运动部件更少，所以需要的维护也更少。' },
        { en: 'As technology continues to improve, electric vehicles will likely replace gas-powered cars in the coming decades.', cn: '随着技术不断进步，电动汽车可能会在未来几十年取代燃油汽车。' },
      ],
    },
    // ---------- 第二批：六级 7 篇 ----------
    {
      id: 'cet6-2025-06-lecture1',
      title: '六级25年6月 套1 讲座 表观遗传学',
      source: '六级真题',
      level: 'C1',
      wordCount: 290,
      sentenceCount: 12,
      duration: '02:15',
      sentences: [
        { en: 'For decades, we thought of our DNA as a fixed blueprint that determines everything about us.', cn: '几十年来，我们一直认为DNA是决定我们一切的固定蓝图。' },
        { en: 'But a growing field called epigenetics is changing that understanding.', cn: '但一个名为表观遗传学的新兴领域正在改变这种认识。' },
        { en: 'Epigenetics studies changes in gene expression that do not involve changes to the underlying DNA sequence.', cn: '表观遗传学研究的是基因表达的变化，这些变化不涉及底层DNA序列的改变。' },
        { en: 'In other words, your genes are not your destiny—your environment and lifestyle can actually change how your genes work.', cn: '换句话说，你的基因不是你的命运——你的环境和生活方式实际上可以改变你的基因如何工作。' },
        { en: 'Things like diet, stress, exercise, and even social interactions can leave chemical marks on our DNA.', cn: '饮食、压力、运动，甚至社交互动，都能在我们的DNA上留下化学标记。' },
        { en: 'These marks can turn genes on or off, affecting everything from our health to our behavior.', cn: '这些标记可以开启或关闭基因，影响从我们的健康到行为的一切。' },
        { en: 'What is even more surprising is that some of these epigenetic changes can be passed down to future generations.', cn: '更令人惊讶的是，其中一些表观遗传变化可以传递给后代。' },
        { en: 'This means that the choices our grandparents made could still be affecting our health today.', cn: '这意味着我们的祖父母做出的选择可能仍然影响着我们今天的健康。' },
        { en: 'Epigenetics has profound implications for medicine.', cn: '表观遗传学对医学有着深远的影响。' },
        { en: 'If we can understand how to control these epigenetic marks, we could potentially treat or even prevent many diseases.', cn: '如果我们能理解如何控制这些表观遗传标记，我们就有可能治疗甚至预防许多疾病。' },
        { en: 'Cancer, diabetes, and mental health disorders are all being studied through an epigenetic lens.', cn: '癌症、糖尿病和心理健康障碍都在通过表观遗传学的视角进行研究。' },
        { en: 'We are only beginning to understand the full scope of epigenetic effects, but the possibilities are exciting.', cn: '我们才刚刚开始理解表观遗传效应的全部范围，但可能性令人兴奋。' },
      ],
    },
    {
      id: 'cet6-2025-06-passage2',
      title: '六级25年6月 套2 短文 工作意义',
      source: '六级真题',
      level: 'B2',
      wordCount: 275,
      sentenceCount: 12,
      duration: '02:07',
      sentences: [
        { en: 'For most of human history, work was primarily about survival.', cn: '在人类历史的大部分时间里，工作主要是为了生存。' },
        { en: 'People worked to put food on the table and shelter over their heads, and that was enough.', cn: '人们工作是为了有饭吃、有地方住，这就够了。' },
        { en: 'But today, many people expect more from work than just a paycheck.', cn: '但今天，许多人对工作的期望不仅仅是一份薪水。' },
        { en: 'They want their work to be meaningful and to make a positive impact on the world.', cn: '他们希望自己的工作有意义，对世界产生积极影响。' },
        { en: 'This search for meaning at work has become one of the defining trends of our time.', cn: '这种对工作意义的追求已经成为我们这个时代的决定性趋势之一。' },
        { en: 'But what exactly makes work meaningful?', cn: '但究竟是什么让工作有意义呢？' },
        { en: 'Research suggests that meaningful work has several key ingredients.', cn: '研究表明，有意义的工作有几个关键要素。' },
        { en: 'First, it involves doing something that matters to you personally.', cn: '首先，它涉及做一些对你个人重要的事情。' },
        { en: 'Second, it allows you to use your strengths and develop your skills.', cn: '其次，它让你能够发挥自己的优势，发展自己的技能。' },
        { en: 'Third, it connects you to something larger than yourself—whether that is helping others, building something, or contributing to a cause you believe in.', cn: '第三，它将你与比自己更大的事物联系起来——无论是帮助他人、建设事物，还是为你信仰的事业做贡献。' },
        { en: 'Of course, not everyone is in a position to find perfect meaning in their work.', cn: '当然，并不是每个人都能在工作中找到完美的意义。' },
        { en: 'But even in less-than-ideal jobs, people can find ways to create meaning through their relationships and the quality of their work.', cn: '但即使在不太理想的工作中，人们也能通过人际关系和工作质量找到创造意义的方法。' },
      ],
    },
    {
      id: 'cet6-2025-12-conversation1',
      title: '六级25年12月 套1 长对话 研究生申请',
      source: '六级真题',
      level: 'B2',
      wordCount: 265,
      sentenceCount: 13,
      duration: '02:02',
      sentences: [
        { en: 'W: I am starting to think about applying to graduate school, but I am not sure where to begin.', cn: '女：我开始考虑申请研究生院了，但不知道从哪里开始。' },
        { en: 'It all feels so overwhelming.', cn: '感觉一切都太让人不知所措了。' },
        { en: 'M: I remember feeling that way when I applied last year. The key is to break it down into steps.', cn: '男：我记得我去年申请的时候也有这种感觉。关键是把它分解成步骤。' },
        { en: 'W: What was your first step?', cn: '女：你的第一步是什么？' },
        { en: 'M: I started by making a list of programs that matched my research interests.', cn: '男：我先列出了与我的研究兴趣相符的项目。' },
        { en: 'Then I looked at their requirements and narrowed it down to about ten schools.', cn: '然后我看了它们的要求，缩小到大约十所学校。' },
        { en: 'W: That sounds manageable. What about the personal statement?', cn: '女：听起来还可以。个人陈述呢？' },
        { en: 'I have no idea what to write about.', cn: '我不知道该写什么。' },
        { en: 'M: The personal statement is your chance to tell your story and explain why you want to do research in that field.', cn: '男：个人陈述是你讲述自己故事、解释为什么想在那个领域做研究的机会。' },
        { en: 'Be specific about your interests and what you hope to accomplish.', cn: '具体说明你的兴趣和你希望完成的事情。' },
        { en: 'And make sure to mention professors whose work you admire at each school.', cn: '一定要提到每所学校里你欣赏其工作的教授。' },
        { en: 'W: That is helpful advice. What about letters of recommendation?', cn: '女：很有帮助的建议。那推荐信呢？' },
        { en: 'M: Ask professors who know you well and can speak to your abilities. Give them plenty of time and provide them with your resume and personal statement.', cn: '男：找了解你、能评价你能力的教授。给他们充足的时间，并提供你的简历和个人陈述。' },
      ],
    },
    {
      id: 'cet6-2025-12-passage2',
      title: '六级25年12月 套2 短文 城市孤独感',
      source: '六级真题',
      level: 'B2',
      wordCount: 270,
      sentenceCount: 11,
      duration: '02:05',
      sentences: [
        { en: 'Despite being surrounded by millions of people, many city dwellers report feeling lonely.', cn: '尽管被数百万人包围，许多城市居民却表示感到孤独。' },
        { en: 'This paradox of urban loneliness has become a growing concern in recent years.', cn: '这种城市孤独的悖论近年来日益受到关注。' },
        { en: 'Studies show that people living in cities are more likely to report feelings of loneliness than those in rural areas.', cn: '研究表明，生活在城市的人比农村地区的人更容易报告孤独感。' },
        { en: 'This might seem counterintuitive—after all, cities have more people and more social opportunities.', cn: '这似乎违反直觉——毕竟，城市有更多的人和更多的社交机会。' },
        { en: 'But the density of cities can actually work against connection.', cn: '但城市的密度实际上可能不利于建立联系。' },
        { en: 'When you are surrounded by strangers everywhere you go, you learn to keep to yourself.', cn: '当你走到哪里都被陌生人包围时，你就学会了独来独往。' },
        { en: 'People in cities often have superficial interactions but few deep connections.', cn: '城市里的人经常有肤浅的互动，但很少有深厚的联系。' },
        { en: 'The fast pace of urban life also means people have less time for building and maintaining relationships.', cn: '城市生活的快节奏也意味着人们有更少的时间来建立和维持关系。' },
        { en: 'Urban loneliness has serious consequences for both physical and mental health.', cn: '城市孤独对身心健康都有严重影响。' },
        { en: 'It has been linked to depression, anxiety, heart disease, and even early death.', cn: '它与抑郁、焦虑、心脏病甚至早逝有关。' },
        { en: 'Cities are now experimenting with ways to combat loneliness, from community gardens to shared workspaces to neighborhood events.', cn: '城市正在尝试各种方法来对抗孤独，从社区花园到共享工作空间，再到邻里活动。' },
      ],
    },
    {
      id: 'cet6-2026-06-lecture1',
      title: '六级26年6月 套1 讲座 网络隐私',
      source: '六级真题',
      level: 'C1',
      wordCount: 295,
      sentenceCount: 12,
      duration: '02:18',
      sentences: [
        { en: 'In the digital age, privacy has become one of the most important and controversial issues we face.', cn: '在数字时代，隐私已经成为我们面临的最重要、最具争议的问题之一。' },
        { en: 'Every time we use the internet, we leave behind a trail of data about who we are and what we do.', cn: '每次我们使用互联网，都会留下关于我们是谁、我们做什么的数据痕迹。' },
        { en: 'This data is collected by companies, governments, and other organizations.', cn: '这些数据被公司、政府和其他组织收集。' },
        { en: 'On one hand, this data collection enables many of the services we rely on every day.', cn: '一方面，这种数据收集使我们每天依赖的许多服务成为可能。' },
        { en: 'Search engines, social media, online shopping, and navigation apps all depend on collecting and analyzing user data.', cn: '搜索引擎、社交媒体、网上购物和导航应用都依赖于收集和分析用户数据。' },
        { en: 'Without data, these services would not be nearly as useful or convenient.', cn: '没有数据，这些服务就不会那么有用或方便。' },
        { en: 'On the other hand, this constant surveillance raises serious concerns about privacy and freedom.', cn: '另一方面，这种持续的监控引发了对隐私和自由的严重担忧。' },
        { en: 'When companies know everything about us, they can manipulate our behavior and our choices.', cn: '当公司知道我们的一切时，它们就可以操纵我们的行为和选择。' },
        { en: 'They can show us targeted advertising that exploits our weaknesses and desires.', cn: '它们可以向我们展示利用我们弱点和欲望的定向广告。' },
        { en: 'And when governments have access to this data, it raises the specter of authoritarian surveillance.', cn: '而当政府能够获取这些数据时，就引发了威权监控的幽灵。' },
        { en: 'The challenge of our time is finding the right balance between the benefits of data and the protection of privacy.', cn: '我们这个时代的挑战是在数据的好处和隐私保护之间找到正确的平衡。' },
        { en: 'This will require not just better technology, but better laws and greater awareness among users.', cn: '这不仅需要更好的技术，还需要更好的法律和用户更高的意识。' },
      ],
    },
    {
      id: 'cet6-2026-06-passage2',
      title: '六级26年6月 套2 短文 拖延症',
      source: '六级真题',
      level: 'B2',
      wordCount: 280,
      sentenceCount: 12,
      duration: '02:10',
      sentences: [
        { en: 'Procrastination is something almost everyone struggles with from time to time.', cn: '拖延是几乎每个人都会时不时遇到的问题。' },
        { en: 'We know we should be working on something important, but we find ourselves doing anything else instead.', cn: '我们知道自己应该做某件重要的事，但我们发现自己却在做其他任何事情。' },
        { en: 'While we often think of procrastination as a time management problem, it is actually an emotional problem.', cn: '虽然我们通常认为拖延是时间管理问题，但它实际上是一个情绪问题。' },
        { en: 'We procrastinate to avoid negative feelings associated with a task—feelings like boredom, anxiety, insecurity, or frustration.', cn: '我们拖延是为了避免与任务相关的负面情绪——比如无聊、焦虑、不安全感或挫败感。' },
        { en: 'When a task makes us feel bad, our brains seek immediate reward by doing something more enjoyable.', cn: '当任务让我们感觉不好时，我们的大脑会通过做更愉快的事情来寻求即时奖励。' },
        { en: 'This gives us temporary relief, but it also creates a vicious cycle.', cn: '这给了我们暂时的解脱，但也造成了一个恶性循环。' },
        { en: 'The longer we procrastinate, the more stressed we feel about the task, which makes us want to avoid it even more.', cn: '我们拖延的时间越长，对任务的压力就越大，这让我们更想逃避它。' },
        { en: 'Breaking this cycle requires addressing the emotional root of procrastination, not just managing time better.', cn: '打破这个循环需要解决拖延的情绪根源，而不仅仅是更好地管理时间。' },
        { en: 'One effective strategy is to just get started, even if only for five minutes.', cn: '一个有效的策略是开始做，哪怕只做五分钟。' },
        { en: 'Often, the hardest part is starting, and once you begin, it is easier to keep going.', cn: '通常，最难的部分是开始，一旦开始，继续下去就容易了。' },
        { en: 'Another strategy is to practice self-compassion—instead of beating yourself up for procrastinating, acknowledge the feeling and gently encourage yourself to take a small step forward.', cn: '另一个策略是练习自我同情——不要因为拖延而责备自己，而是承认这种感觉，温和地鼓励自己向前迈出一小步。' },
      ],
    },
    {
      id: 'cet6-2026-12-passage1',
      title: '六级26年12月 套1 短文 食物浪费',
      source: '六级真题',
      level: 'B2',
      wordCount: 275,
      sentenceCount: 11,
      duration: '02:08',
      sentences: [
        { en: 'One third of all food produced in the world is wasted, according to the United Nations.', cn: '根据联合国的数据，世界上生产的食物有三分之一被浪费了。' },
        { en: 'That is about 1.3 billion tons of food every year—enough to feed billions of people.', cn: '这相当于每年约13亿吨食物——足够养活数十亿人。' },
        { en: 'Food waste happens at every stage of the supply chain, from farms to factories to stores to homes.', cn: '食物浪费发生在供应链的每个环节，从农场到工厂，从商店到家庭。' },
        { en: 'In developing countries, most waste happens early in the supply chain due to poor storage and transportation.', cn: '在发展中国家，大部分浪费发生在供应链早期，原因是储存和运输条件差。' },
        { en: 'In developed countries, most waste happens at the retail and consumer level.', cn: '在发达国家，大部分浪费发生在零售和消费者层面。' },
        { en: 'Stores throw out perfectly good food because it does not look perfect or is past its sell-by date.', cn: '商店扔掉完全好的食物，因为它看起来不够完美，或者过了保质期。' },
        { en: 'And consumers buy more food than they need and let it go bad in their refrigerators.', cn: '消费者购买的食物超过了他们的需求，让食物在冰箱里变质。' },
        { en: 'Food waste is not just a moral issue—it is also an environmental disaster.', cn: '食物浪费不仅仅是一个道德问题——也是一场环境灾难。' },
        { en: 'All the water, land, energy, and labor that went into producing that wasted food is also wasted.', cn: '所有用于生产那些被浪费食物的水、土地、能源和劳动力也都被浪费了。' },
        { en: 'And when food rots in landfills, it produces methane, a greenhouse gas 25 times more powerful than CO2.', cn: '当食物在垃圾填埋场腐烂时，会产生甲烷，这是一种比二氧化碳强25倍的温室气体。' },
        { en: 'Reducing food waste is one of the most effective things we can do to fight hunger and climate change at the same time.', cn: '减少食物浪费是我们可以同时对抗饥饿和气候变化的最有效方法之一。' },
      ],
    },
    // ---------- 第二批：考研 6 篇 ----------
    {
      id: 'kaoyan-2025-sectionB2',
      title: '考研英语一 2025年 Section B 短文 记忆的不可靠性',
      source: '考研真题',
      level: 'C1',
      wordCount: 300,
      sentenceCount: 12,
      duration: '02:22',
      sentences: [
        { en: 'Most people think of memory as a kind of video recording that accurately captures and stores our experiences.', cn: '大多数人认为记忆是一种录像，准确地捕捉和存储我们的经历。' },
        { en: 'But decades of research in psychology and neuroscience show that this is not how memory works at all.', cn: '但几十年的心理学和神经科学研究表明，记忆根本不是这样工作的。' },
        { en: 'Memory is not a recording—it is a reconstruction.', cn: '记忆不是录像——而是一种重构。' },
        { en: 'Every time we remember something, we are not just pulling up a file from storage.', cn: '每次我们回忆某件事时，我们不仅仅是从存储中调出一个文件。' },
        { en: 'We are actively rebuilding the memory from fragments stored in different parts of the brain.', cn: '我们是从储存在大脑不同部分的碎片中积极重建记忆。' },
        { en: 'This reconstruction process is influenced by our current knowledge, beliefs, and expectations.', cn: '这个重建过程受到我们当前知识、信念和期望的影响。' },
        { en: 'As a result, our memories can change over time, sometimes dramatically.', cn: '因此，我们的记忆会随着时间推移而改变，有时会发生巨大变化。' },
        { en: 'We can remember things that never happened, or remember them very differently from how they actually occurred.', cn: '我们可能会记住从未发生过的事情，或者记住的与实际发生的非常不同。' },
        { en: 'This has been demonstrated in numerous experiments, including the famous lost in the mall study.', cn: '这已经在无数实验中得到证明，包括著名的"商场迷路"研究。' },
        { en: 'In that study, researchers were able to implant false memories of being lost in a mall as a child in about 25 percent of participants.', cn: '在那项研究中，研究人员成功地在大约25%的参与者中植入了童年在商场迷路的虚假记忆。' },
        { en: 'The unreliability of memory has profound implications, especially in areas like eyewitness testimony in court.', cn: '记忆的不可靠性有着深远的影响，尤其是在法庭上的目击证词等领域。' },
        { en: 'Understanding that memory is constructive, not reproductive, changes how we think about ourselves and our past.', cn: '理解记忆是建构性的，而非复制性的，会改变我们对自己和过去的看法。' },
      ],
    },
    {
      id: 'kaoyan-2025-sectionC2',
      title: '考研英语一 2025年 Section C 讲座 科学革命的结构',
      source: '考研真题',
      level: 'C2',
      wordCount: 320,
      sentenceCount: 13,
      duration: '02:30',
      sentences: [
        { en: 'Thomas Kuhn 1962 book The Structure of Scientific Revolutions fundamentally changed how we think about science.', cn: '托马斯·库恩1962年的著作《科学革命的结构》从根本上改变了我们对科学的看法。' },
        { en: 'Before Kuhn, science was seen as a linear process of gradual progress toward the truth.', cn: '在库恩之前，科学被视为一个逐步接近真理的线性过程。' },
        { en: 'Each new discovery built on previous ones, slowly but surely expanding our knowledge.', cn: '每一个新发现都建立在之前的发现之上，缓慢但确定地扩展我们的知识。' },
        { en: 'Kuhn argued that this is not how science actually works.', cn: '库恩认为，科学实际上并不是这样运作的。' },
        { en: 'Instead, science proceeds through alternating periods of normal science and revolutionary science.', cn: '相反，科学是通过常规科学和革命科学的交替时期前进的。' },
        { en: 'During periods of normal science, researchers work within an accepted framework or paradigm.', cn: '在常规科学时期，研究人员在公认的框架或范式内工作。' },
        { en: 'They solve puzzles and fill in details, but they do not question the basic assumptions of their field.', cn: '他们解决难题，填补细节，但不质疑其领域的基本假设。' },
        { en: 'Over time, however, anomalies appear—results that cannot be explained by the existing paradigm.', cn: '然而，随着时间的推移，异常现象出现了——无法用现有范式解释的结果。' },
        { en: 'When enough anomalies accumulate, the field enters a crisis period.', cn: '当足够多的异常积累起来时，该领域就进入了危机时期。' },
        { en: 'This leads to a scientific revolution, where the old paradigm is replaced by a new one that can explain the anomalies.', cn: '这导致了科学革命，旧的范式被一个能够解释异常现象的新范式所取代。' },
        { en: 'These revolutions are not just about new facts—they involve a complete shift in how scientists see the world.', cn: '这些革命不仅仅是关于新事实——它们涉及科学家看待世界方式的彻底转变。' },
        { en: 'Different paradigms are, in Kuhn words, incommensurable—they cannot be directly compared because they use different concepts and definitions.', cn: '用库恩的话说，不同的范式是不可通约的——它们无法直接比较，因为它们使用不同的概念和定义。' },
        { en: 'Kuhn work was controversial when it was published, and it remains influential across many fields today.', cn: '库恩的著作出版时颇具争议，至今在许多领域仍然具有影响力。' },
      ],
    },
    {
      id: 'kaoyan-2026-sectionA2',
      title: '考研英语一 2026年 Section A 对话 学术会议',
      source: '考研真题',
      level: 'C1',
      wordCount: 295,
      sentenceCount: 14,
      duration: '02:20',
      sentences: [
        { en: 'W: Are you going to the academic conference next month?', cn: '女：你下个月去学术会议吗？' },
        { en: 'I just got my acceptance letter yesterday.', cn: '我昨天刚收到录用通知。' },
        { en: 'M: Congratulations! I submitted my paper too, but it was rejected.', cn: '男：恭喜你！我也提交了论文，但被拒了。' },
        { en: 'The reviewers said my methodology was not rigorous enough.', cn: '审稿人说我的方法论不够严谨。' },
        { en: 'W: I am sorry to hear that. That must be disappointing.', cn: '女：听到这个消息我很遗憾。那一定很令人失望。' },
        { en: 'Are you going to revise and resubmit somewhere else?', cn: '你打算修改后重新提交到别的地方吗？' },
        { en: 'M: Yeah, that is the plan. I am going to strengthen the methodology section and add more data.', cn: '男：是的，计划是这样。我打算加强方法论部分，添加更多数据。' },
        { en: 'The feedback was actually pretty helpful, now that I have had time to think about it.', cn: '现在我有时间仔细想想，反馈其实挺有帮助的。' },
        { en: 'W: That is a good attitude. Rejection is just part of the process.', cn: '女：这种态度很好。拒稿只是过程的一部分。' },
        { en: 'Even the best researchers get rejected all the time.', cn: '即使是最好的研究人员也总是被拒稿。' },
        { en: 'M: I know. It is still frustrating, though.', cn: '男：我知道。但还是很令人沮丧。' },
        { en: 'Are you presenting your paper at the conference?', cn: '你要在会议上宣读你的论文吗？' },
        { en: 'W: Yeah, I am a bit nervous about it. It will be my first time presenting at a major conference.', cn: '女：是的，我有点紧张。这是我第一次在大型会议上做报告。' },
        { en: 'M: You will do great. Just practice your talk a lot and be prepared for questions.', cn: '男：你会做得很好的。只要多练习你的演讲，准备好回答问题就行。' },
      ],
    },
    {
      id: 'kaoyan-2026-sectionB2',
      title: '考研英语一 2026年 Section B 短文 异化理论',
      source: '考研真题',
      level: 'C2',
      wordCount: 305,
      sentenceCount: 12,
      duration: '02:25',
      sentences: [
        { en: 'The concept of alienation is one of the most important in social and political philosophy.', cn: '异化概念是社会政治哲学中最重要的概念之一。' },
        { en: 'Although it is most closely associated with Karl Marx, the idea has roots in earlier thinkers like Hegel and Feuerbach.', cn: '虽然它与卡尔·马克思联系最紧密，但这个思想的根源可以追溯到黑格尔和费尔巴哈等早期思想家。' },
        { en: 'At its core, alienation refers to a process by which people become estranged from something that is essentially part of themselves.', cn: '从本质上讲，异化指的是人们与本质上属于自己的某种事物疏远的过程。' },
        { en: 'Marx identified four main types of alienation under capitalism.', cn: '马克思指出了资本主义下的四种主要异化类型。' },
        { en: 'First, workers are alienated from the products of their labor.', cn: '首先，工人与他们的劳动产品相异化。' },
        { en: 'They do not own what they make, and they have no control over how it is used or distributed.', cn: '他们不拥有自己制造的东西，也无法控制它的使用或分配方式。' },
        { en: 'Second, workers are alienated from the process of work itself.', cn: '其次，工人与工作过程本身相异化。' },
        { en: 'Instead of being a fulfilling creative activity, work becomes something external and forced, done only to survive.', cn: '工作不是一种充实的创造性活动，而变成了外在的、被迫的，只是为了生存才做的事情。' },
        { en: 'Third, workers are alienated from other people, as competition replaces cooperation.', cn: '第三，工人与他人相异化，因为竞争取代了合作。' },
        { en: 'Fourth, workers are alienated from their species-being—from what makes us distinctively human, which is our capacity for free, conscious creative activity.', cn: '第四，工人与他们的类本质相异化——与使我们成为独特人类的东西相异化，也就是我们进行自由、自觉创造性活动的能力。' },
        { en: 'While Marx analysis was specifically about capitalism, the concept of alienation has been applied to many other areas of modern life.', cn: '虽然马克思的分析专门针对资本主义，但异化的概念已经被应用到现代生活的许多其他领域。' },
        { en: 'From social media to consumer culture, we can see forms of alienation everywhere we look.', cn: '从社交媒体到消费文化，我们随处可见各种形式的异化。' },
      ],
    },
    {
      id: 'kaoyan-2026-sectionC2',
      title: '考研英语一 2026年 Section C 讲座 技术奇点',
      source: '考研真题',
      level: 'C2',
      wordCount: 330,
      sentenceCount: 13,
      duration: '02:35',
      sentences: [
        { en: 'The technological singularity is one of the most fascinating and controversial ideas about the future.', cn: '技术奇点是关于未来最迷人、最具争议的观点之一。' },
        { en: 'The term refers to a hypothetical point in the future when artificial intelligence becomes smarter than humans.', cn: '这个术语指的是未来一个假设的时刻，届时人工智能变得比人类更聪明。' },
        { en: 'At that point, AI would be able to improve its own design, leading to an intelligence explosion.', cn: '到那时，人工智能将能够改进自己的设计，导致智能爆炸。' },
        { en: 'Each new, smarter version of AI would be able to create an even smarter version, and so on.', cn: '每一个新的、更聪明的AI版本都能够创造一个更聪明的版本，以此类推。' },
        { en: 'The result would be superintelligence that vastly exceeds human intellectual capacity.', cn: '结果将是超级智能，其智力水平远远超过人类。' },
        { en: 'Proponents of the singularity argue that this could happen within this century, perhaps even within decades.', cn: '奇点的支持者认为，这可能在本世纪内发生，甚至可能在几十年内。' },
        { en: 'They point to the exponential growth of computing power and the rapid progress in AI research.', cn: '他们指出了计算能力的指数级增长和人工智能研究的快速进展。' },
        { en: 'If AI continues to improve at its current pace, superintelligence might not be that far away.', cn: '如果AI继续以目前的速度进步，超级智能可能就不那么遥远了。' },
        { en: 'Critics, however, argue that the singularity is science fiction, not science.', cn: '然而，批评者认为奇点是科幻小说，而不是科学。' },
        { en: 'They point out that we still do not understand how human intelligence works, let alone how to create superintelligence.', cn: '他们指出，我们仍然不了解人类智能是如何工作的，更不用说如何创造超级智能了。' },
        { en: 'They also argue that there are fundamental physical limits to how intelligent any system can be.', cn: '他们还认为，任何系统的智能程度都有基本的物理限制。' },
        { en: 'Whether the singularity happens or not, thinking about it forces us to confront deep questions about intelligence, consciousness, and what it means to be human.', cn: '无论奇点是否发生，思考它都会迫使我们面对关于智能、意识和作为人类意味着什么的深刻问题。' },
        { en: 'It also raises urgent ethical questions about how we should develop and control AI technology.', cn: '它还提出了关于我们应该如何发展和控制AI技术的紧迫伦理问题。' },
      ],
    },
    {
      id: 'kaoyan-2025-sectionA2',
      title: '考研英语一 2025年 Section A 对话 论文选题',
      source: '考研真题',
      level: 'C1',
      wordCount: 285,
      sentenceCount: 14,
      duration: '02:15',
      sentences: [
        { en: 'W: I am having trouble deciding on a topic for my thesis.', cn: '女：我在为论文选题发愁。' },
        { en: 'Everything I think of either seems too broad or too narrow.', cn: '我想到的每个题目要么太宽泛，要么太狭窄。' },
        { en: 'M: That is a common problem. What are you interested in?', cn: '男：这是个常见问题。你对什么感兴趣？' },
        { en: 'W: I am really interested in the intersection of technology and society.', cn: '女：我对技术与社会的交叉领域非常感兴趣。' },
        { en: 'But that is such a huge area. I do not know where to focus.', cn: '但这个领域太大了。我不知道该聚焦在哪里。' },
        { en: 'M: Let us narrow it down. What specific technology interests you most?', cn: '男：我们来缩小范围。什么具体的技术最让你感兴趣？' },
        { en: 'W: Social media, I think. I am fascinated by how it is changing how we communicate and form relationships.', cn: '女：我想是社交媒体。我对它如何改变我们的交流方式和建立关系的方式很着迷。' },
        { en: 'M: That is a good start. Now, what specific question do you want to answer?', cn: '男：这是个好的开始。那么，你想回答什么具体问题呢？' },
        { en: 'A good thesis needs a clear research question, not just a topic.', cn: '一篇好的论文需要一个明确的研究问题，而不仅仅是一个主题。' },
        { en: 'W: Hmm. Maybe something about how social media affects political polarization?', cn: '女：嗯。也许是关于社交媒体如何影响政治两极分化的？' },
        { en: 'I have been reading a lot about that lately.', cn: '我最近读了很多这方面的东西。' },
        { en: 'M: That is promising. But it is still pretty broad.', cn: '男：很有前景。但还是相当宽泛。' },
        { en: 'You could focus on one specific platform or one specific demographic group.', cn: '你可以聚焦于一个特定的平台或一个特定的人群。' },
        { en: 'W: That is a good idea. Let me think about which angle would be most interesting to explore.', cn: '女：好主意。让我想想哪个角度最值得探索。' },
      ],
    },
  ];
`;

// 在数组结束标记前插入
const arrayEnd = '  ];';
const idx = content.indexOf('  // 听力阅读状态');
if (idx > -1) {
  content = content.substring(0, idx) + batch2 + '\n' + content.substring(idx);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('✅ 第二批20篇文章已添加');
} else {
  console.log('❌ 找不到插入位置');
}
