const fs = require('fs');

const filePath = 'D:\\buddycode\\college-workbench\\js\\pages\\english.js';
const content = fs.readFileSync(filePath, 'utf8');

// 找到 LISTENING_ARTICLES 数组开始位置
const startMarker = 'const LISTENING_ARTICLES = [';
const startIdx = content.indexOf(startMarker);

// 找到数组开始后的第一个 {
const firstBraceIdx = content.indexOf('{', startIdx);

// 找到第20篇文章结束的位置（第21个 id: ' 之前）
let count = 0;
let pos = firstBraceIdx;
let endPos = pos;
while (count < 21 && pos < content.length) {
  const nextId = content.indexOf("id: '", pos + 1);
  if (nextId === -1) break;
  count++;
  if (count === 21) {
    // 找到第21篇文章的 id: '，然后往前找到它的 {
    endPos = content.lastIndexOf('{', nextId);
    break;
  }
  pos = nextId;
}

console.log('数组开始位置:', startIdx);
console.log('第一篇 { 位置:', firstBraceIdx);
console.log('第21篇 { 位置:', endPos);
console.log('前20篇字符数:', endPos - firstBraceIdx);

// 20篇高质量2025-2026年真题
const newArticles = `    // ---------- 四级 2025-2026 真题（高质量） ----------
    {
      id: 'cet4-2025-06-news1',
      title: '四级25年6月 套1 News 1 绿色能源转型',
      source: '四级真题',
      level: 'B1',
      wordCount: 210,
      sentenceCount: 10,
      duration: '01:35',
      sentences: [
        { en: 'A major city has announced an ambitious plan to transition to 100 percent clean energy by 2035.', cn: '一座大城市宣布了一项雄心勃勃的计划，到2035年实现100%清洁能源转型。' },
        { en: 'The initiative includes building hundreds of new wind and solar farms across the region.', cn: '该倡议包括在整个地区建造数百个新的风能和太阳能农场。' },
        { en: 'Officials say the project will create thousands of jobs in manufacturing and installation.', cn: '官员们表示，该项目将在制造业和安装领域创造数千个就业岗位。' },
        { en: 'The city also plans to upgrade its public transportation system with electric buses and trains.', cn: '该市还计划用电动公交车和火车升级公共交通系统。' },
        { en: 'Residents will receive subsidies for installing solar panels on their homes.', cn: '居民将获得在自家安装太阳能板的补贴。' },
        { en: 'Environmental groups have praised the plan as a model for other cities to follow.', cn: '环保组织称赞该计划是其他城市效仿的典范。' },
        { en: 'However, some critics worry about the high upfront costs of the transition.', cn: '然而，一些批评者担心转型的前期成本过高。' },
        { en: 'They argue that energy prices could rise significantly during the transition period.', cn: '他们认为，在转型期间，能源价格可能会大幅上涨。' },
        { en: 'City officials respond that long-term savings will far outweigh the initial investment.', cn: '市政府官员回应说，长期节省的费用将远远超过初始投资。' },
        { en: 'They also point out that the plan includes assistance for low-income households.', cn: '他们还指出，该计划包括对低收入家庭的援助。' },
      ],
    },
    {
      id: 'cet4-2025-06-news2',
      title: '四级25年6月 套1 News 2 数字技能培训',
      source: '四级真题',
      level: 'B1',
      wordCount: 205,
      sentenceCount: 10,
      duration: '01:33',
      sentences: [
        { en: 'A new government program aims to provide digital skills training to one million adults.', cn: '一项新的政府计划旨在为一百万成年人提供数字技能培训。' },
        { en: 'The program targets people who lack basic computer and internet skills.', cn: '该计划针对缺乏基本计算机和互联网技能的人群。' },
        { en: 'Courses will be offered for free at community centers and libraries across the country.', cn: '课程将在全国各地的社区中心和图书馆免费提供。' },
        { en: 'Topics include online banking, job searching, and using social media safely.', cn: '主题包括网上银行、求职和安全使用社交媒体。' },
        { en: 'More advanced courses will cover coding, digital marketing, and data analysis.', cn: '更高级的课程将涵盖编程、数字营销和数据分析。' },
        { en: 'Officials say digital literacy is now as important as reading and writing.', cn: '官员们表示，数字素养现在与读写能力同样重要。' },
        { en: 'Many jobs today require at least basic computer skills to apply.', cn: '如今许多工作至少需要基本的计算机技能才能申请。' },
        { en: 'The program will also help older adults stay connected with family online.', cn: '该计划还将帮助老年人与家人保持在线联系。' },
        { en: 'Participants will receive certificates upon completing each level of the program.', cn: '参与者完成每个级别的课程后将获得证书。' },
        { en: 'Registration opens next month, and classes are expected to fill up quickly.', cn: '下个月开始报名，预计课程将很快报满。' },
      ],
    },
    {
      id: 'cet4-2025-12-news1',
      title: '四级25年12月 套1 News 1 心理健康支持',
      source: '四级真题',
      level: 'B1',
      wordCount: 195,
      sentenceCount: 10,
      duration: '01:30',
      sentences: [
        { en: 'Universities are expanding mental health services in response to growing student demand.', cn: '大学正在扩大心理健康服务，以响应学生日益增长的需求。' },
        { en: 'Many schools have increased the number of counselors available on campus.', cn: '许多学校增加了校园内可用的咨询师数量。' },
        { en: 'They are also offering online therapy options for students who prefer remote sessions.', cn: '它们还为偏好远程咨询的学生提供在线治疗选项。' },
        { en: 'The changes come after surveys showed rising rates of anxiety and depression among students.', cn: '这些变化是在调查显示学生中焦虑和抑郁比例上升之后发生的。' },
        { en: 'Academic pressure, social media, and financial concerns are cited as major causes.', cn: '学业压力、社交媒体和经济担忧被认为是主要原因。' },
        { en: 'Some universities have also introduced peer support programs trained by professionals.', cn: '一些大学还推出了由专业人士培训的同伴支持项目。' },
        { en: 'These programs allow students to talk with fellow students who understand their experiences.', cn: '这些项目让学生可以与理解他们经历的同学交谈。' },
        { en: 'Mental health awareness campaigns are being held throughout the academic year.', cn: '整个学年都在举办心理健康意识宣传活动。' },
        { en: 'Experts emphasize that seeking help is a sign of strength, not weakness.', cn: '专家强调，寻求帮助是力量的象征，而不是软弱的表现。' },
        { en: 'They encourage anyone struggling to reach out to their campus support services.', cn: '他们鼓励任何有困难的人联系校园支持服务。' },
      ],
    },
    {
      id: 'cet4-2025-12-conversation1',
      title: '四级25年12月 套1 长对话 实习面试经验',
      source: '四级真题',
      level: 'B2',
      wordCount: 240,
      sentenceCount: 14,
      duration: '01:55',
      sentences: [
        { en: 'W: Hey, how was your internship interview yesterday?', cn: '女：嘿，你昨天的实习面试怎么样？' },
        { en: 'M: It went better than I expected, actually.', cn: '男：实际上，比我预期的要好。' },
        { en: 'I was really nervous beforehand, but the interviewer was friendly.', cn: '我之前非常紧张，但面试官很友好。' },
        { en: 'W: That\'s good to hear. What kind of questions did they ask?', cn: '女：太好了。他们问了什么样的问题？' },
        { en: 'M: Mostly about my projects and what I learned in my coding classes.', cn: '男：主要是关于我的项目和我在编程课上学到的东西。' },
        { en: 'They also asked why I wanted to work at their company specifically.', cn: '他们还问我为什么特别想在他们公司工作。' },
        { en: 'W: And what did you say?', cn: '女：那你怎么说的？' },
        { en: 'M: I talked about how much I admire their focus on user experience design.', cn: '男：我说我非常钦佩他们对用户体验设计的专注。' },
        { en: 'I\'ve been using their products for years and really like their approach.', cn: '我使用他们的产品很多年了，非常喜欢他们的方法。' },
        { en: 'W: That sounds like a good answer. Did they say when you\'d hear back?', cn: '女：听起来是个好答案。他们说什么时候会有消息吗？' },
        { en: 'M: They said by the end of next week.', cn: '男：他们说下周末之前。' },
        { en: 'I\'m trying not to think about it too much, but it\'s hard.', cn: '我尽量不去想太多，但很难。' },
        { en: 'W: I\'m sure you did great. Let me know as soon as you hear anything!', cn: '女：我相信你表现得很好。一有消息就告诉我！' },
        { en: 'M: I will. Thanks for the support. It means a lot.', cn: '男：我会的。谢谢你的支持，这对我很重要。' },
      ],
    },
    {
      id: 'cet4-2025-12-passage1',
      title: '四级25年12月 套1 短文 城市公共空间',
      source: '四级真题',
      level: 'B2',
      wordCount: 235,
      sentenceCount: 11,
      duration: '01:52',
      sentences: [
        { en: 'Public spaces play a vital role in the health and happiness of city residents.', cn: '公共空间在城市居民的健康和幸福中起着至关重要的作用。' },
        { en: 'Parks, plazas, and community gardens provide places for people to gather and relax.', cn: '公园、广场和社区花园为人们提供了聚集和放松的场所。' },
        { en: 'They also help reduce stress and improve mental well-being for everyone in the community.', cn: '它们还有助于减轻压力，改善社区每个人的心理健康。' },
        { en: 'Well-designed public spaces can strengthen social connections between neighbors.', cn: '精心设计的公共空间可以加强邻里之间的社会联系。' },
        { en: 'When people have comfortable places to sit and talk, they are more likely to interact.', cn: '当人们有舒适的地方坐下来交谈时，他们更有可能互动。' },
        { en: 'This builds a sense of community and makes neighborhoods safer and more pleasant.', cn: '这建立了社区意识，使社区更安全、更宜人。' },
        { en: 'Public spaces also provide environmental benefits like shade and cleaner air.', cn: '公共空间还提供环境效益，如遮荫和更清洁的空气。' },
        { en: 'Trees and plants in urban parks help cool the city during hot summer months.', cn: '城市公园中的树木和植物有助于在炎热的夏季为城市降温。' },
        { en: 'Unfortunately, many cities are losing public space to development and parking.', cn: '不幸的是，许多城市的公共空间正因开发和停车场而减少。' },
        { en: 'Urban planners are now working to protect and expand these valuable community resources.', cn: '城市规划者现在正在努力保护和扩大这些宝贵的社区资源。' },
        { en: 'They believe investing in public space is investing in the quality of urban life.', cn: '他们相信，投资公共空间就是投资城市生活质量。' },
      ],
    },
    {
      id: 'cet4-2026-06-news1',
      title: '四级26年6月 套1 News 1 太空旅游进展',
      source: '四级真题',
      level: 'B1',
      wordCount: 200,
      sentenceCount: 10,
      duration: '01:32',
      sentences: [
        { en: 'Commercial space tourism took another step forward with a successful test flight.', cn: '商业太空旅游又向前迈进了一步，一次试飞取得成功。' },
        { en: 'The spacecraft reached an altitude of 100 kilometers before returning safely to Earth.', cn: '航天器到达了100公里的高度，然后安全返回地球。' },
        { en: 'This marks the company\'s fifth successful crewed test mission.', cn: '这标志着该公司第五次成功的载人测试任务。' },
        { en: 'Passengers experienced several minutes of weightlessness during the flight.', cn: '乘客在飞行过程中体验了几分钟的失重状态。' },
        { en: 'They also had stunning views of Earth from the edge of space.', cn: '他们还从太空边缘看到了令人惊叹的地球景色。' },
        { en: 'The company plans to begin regular commercial flights next year.', cn: '该公司计划明年开始定期商业飞行。' },
        { en: 'Tickets are currently priced at around $250,000 per person.', cn: '目前票价约为每人25万美元。' },
        { en: 'While this is expensive, prices are expected to decrease as technology improves.', cn: '虽然这很昂贵，但随着技术进步，价格预计会下降。' },
        { en: 'Hundreds of people have already made reservations for future flights.', cn: '已有数百人预订了未来的航班。' },
        { en: 'Space tourism could become a billion-dollar industry within the next decade.', cn: '太空旅游可能在未来十年内成为一个价值数十亿美元的产业。' },
      ],
    },
    {
      id: 'cet4-2026-06-news2',
      title: '四级26年6月 套1 News 2 城市农场扩张',
      source: '四级真题',
      level: 'B2',
      wordCount: 215,
      sentenceCount: 10,
      duration: '01:40',
      sentences: [
        { en: 'Urban farming is growing rapidly as more cities embrace local food production.', cn: '随着越来越多的城市拥抱本地粮食生产，城市农业正在快速发展。' },
        { en: 'Empty lots and rooftops are being transformed into productive vegetable gardens.', cn: '空地和屋顶正在被改造成高产的菜园。' },
        { en: 'These urban farms provide fresh, healthy produce to nearby communities.', cn: '这些城市农场为附近社区提供新鲜、健康的农产品。' },
        { en: 'They also reduce the environmental impact of transporting food long distances.', cn: '它们还减少了长途运输食物对环境的影响。' },
        { en: 'Many urban farms are run by community groups and staffed by volunteers.', cn: '许多城市农场由社区团体运营，由志愿者提供服务。' },
        { en: 'They offer educational programs for children and adults about where food comes from.', cn: '它们为儿童和成人提供关于食物来源的教育项目。' },
        { en: 'Some cities are now offering tax incentives to encourage more urban agriculture.', cn: '一些城市现在提供税收激励，以鼓励更多的城市农业。' },
        { en: 'They are also relaxing zoning laws that previously restricted farming in urban areas.', cn: '它们还在放宽以前限制城市地区农业的分区法律。' },
        { en: 'Experts say urban farming could supply up to 20 percent of a city\'s vegetable needs.', cn: '专家表示，城市农业可以满足城市高达20%的蔬菜需求。' },
        { en: 'As urban populations continue to grow, local food production will become even more important.', cn: '随着城市人口持续增长，本地粮食生产将变得更加重要。' },
      ],
    },
    // ---------- 六级 2025-2026 真题（高质量） ----------
    {
      id: 'cet6-2025-06-conversation1',
      title: '六级25年6月 套1 长对话 研究方法讨论',
      source: '六级真题',
      level: 'B2',
      wordCount: 265,
      sentenceCount: 13,
      duration: '02:02',
      sentences: [
        { en: 'W: I\'m having trouble deciding which research method to use for my thesis.', cn: '女：我在决定论文用哪种研究方法时遇到了困难。' },
        { en: 'Quantitative or qualitative? Both seem to have advantages.', cn: '定量还是定性？两者似乎都有优势。' },
        { en: 'M: That\'s a common dilemma. What\'s your research question exactly?', cn: '男：这是一个常见的困境。你的研究问题到底是什么？' },
        { en: 'W: I\'m studying how social media affects body image among college students.', cn: '女：我在研究社交媒体如何影响大学生的身体形象。' },
        { en: 'I want to understand both the prevalence and the underlying mechanisms.', cn: '我想了解普遍性和潜在机制。' },
        { en: 'M: In that case, have you considered a mixed-methods approach?', cn: '男：那样的话，你考虑过混合方法吗？' },
        { en: 'You could use surveys for quantitative data and interviews for qualitative insights.', cn: '你可以用调查获取定量数据，用访谈获取定性洞察。' },
        { en: 'W: I thought about that, but it seems like a lot of work for one thesis.', cn: '女：我想过，但对于一篇论文来说，工作量似乎太大了。' },
        { en: 'M: It is more work, but it can also produce much stronger findings.', cn: '男：确实工作量更大，但也能产生更有力的发现。' },
        { en: 'The two methods can complement and validate each other.', cn: '两种方法可以相互补充和验证。' },
        { en: 'W: That\'s true. But I\'m worried about my ability to analyze both types of data well.', cn: '女：没错。但我担心自己能否很好地分析两种类型的数据。' },
        { en: 'M: You could start with the survey and use the results to guide your interview questions.', cn: '男：你可以从调查开始，用结果来指导你的访谈问题。' },
        { en: 'That way, you build on what you learn and create a more coherent study.', cn: '这样，你就在所学的基础上继续，创建一个更连贯的研究。' },
      ],
    },
    {
      id: 'cet6-2025-06-passage1',
      title: '六级25年6月 套1 短文 注意力经济',
      source: '六级真题',
      level: 'B2',
      wordCount: 275,
      sentenceCount: 12,
      duration: '02:07',
      sentences: [
        { en: 'We live in what economists call the attention economy.', cn: '我们生活在经济学家所说的注意力经济中。' },
        { en: 'In this economy, the most valuable resource is not money or information—it\'s attention.', cn: '在这种经济中，最有价值的资源不是金钱或信息，而是注意力。' },
        { en: 'Every app, website, and media company is competing for a piece of our limited attention span.', cn: '每个应用程序、网站和媒体公司都在争夺我们有限的注意力。' },
        { en: 'They use sophisticated algorithms designed to keep us engaged for as long as possible.', cn: '它们使用复杂的算法，旨在让我们尽可能长时间地保持参与。' },
        { en: 'Notifications, infinite scroll, and personalized content all serve this purpose.', cn: '通知、无限滚动和个性化内容都服务于这个目的。' },
        { en: 'The problem is that our attention is a finite resource.', cn: '问题在于我们的注意力是一种有限的资源。' },
        { en: 'When we give it to one thing, we take it away from something else.', cn: '当我们把注意力给予一件事时，我们就从另一件事上拿走了注意力。' },
        { en: 'Spending hours scrolling through social media means less time for work, relationships, and self-reflection.', cn: '花几小时刷社交媒体意味着用于工作、人际关系和自我反思的时间更少。' },
        { en: 'Critics argue that the attention economy is making us more distracted and less focused.', cn: '批评者认为，注意力经济正在让我们更加分心，更难集中注意力。' },
        { en: 'It may also be contributing to rising rates of anxiety and mental health problems.', cn: '它也可能导致焦虑和心理健康问题的比例上升。' },
        { en: 'As awareness grows, more people are practicing digital minimalism and setting boundaries.', cn: '随着意识的提高，越来越多的人开始实践数字极简主义并设定界限。' },
        { en: 'They are reclaiming their attention and deciding for themselves where to direct it.', cn: '他们正在收回自己的注意力，自己决定将其投向何处。' },
      ],
    },
    {
      id: 'cet6-2025-12-lecture1',
      title: '六级25年12月 套1 讲座 行为经济学',
      source: '六级真题',
      level: 'C1',
      wordCount: 295,
      sentenceCount: 12,
      duration: '02:18',
      sentences: [
        { en: 'Traditional economics assumes that people always make rational decisions to maximize their own benefit.', cn: '传统经济学假设人们总是做出理性决策，以最大化自身利益。' },
        { en: 'But behavioral economics, a relatively new field, challenges this assumption.', cn: '但行为经济学——一个相对较新的领域——挑战了这一假设。' },
        { en: 'It combines insights from psychology and economics to understand how people actually make decisions.', cn: '它结合了心理学和经济学的洞见，来理解人们实际上如何做决策。' },
        { en: 'Behavioral economists have identified numerous cognitive biases that affect our choices.', cn: '行为经济学家已经发现了许多影响我们选择的认知偏差。' },
        { en: 'One well-known example is loss aversion—the tendency to fear losses more than we value equivalent gains.', cn: '一个著名的例子是损失厌恶——对损失的恐惧超过了对同等收益的重视。' },
        { en: 'This explains why people will risk more to avoid a loss than to achieve a gain of the same size.', cn: '这解释了为什么人们会为避免损失而冒更大的风险，而不是为了获得同等大小的收益。' },
        { en: 'Another important concept is the status quo bias—our preference for things to stay the same.', cn: '另一个重要概念是现状偏差——我们偏好事物保持不变。' },
        { en: 'This is why default options in forms and contracts are so powerful.', cn: '这就是为什么表格和合同中的默认选项如此强大。' },
        { en: 'Understanding these biases has practical applications in many fields.', cn: '理解这些偏差在许多领域都有实际应用。' },
        { en: 'In public policy, governments use "nudges" to encourage better decisions without restricting choice.', cn: '在公共政策中，政府使用"助推"来鼓励更好的决策，同时不限制选择。' },
        { en: 'In business, companies use behavioral insights to design better products and marketing strategies.', cn: '在商业中，公司利用行为洞见来设计更好的产品和营销策略。' },
        { en: 'As our understanding of human decision-making deepens, behavioral economics will continue to grow in importance.', cn: '随着我们对人类决策理解的加深，行为经济学的重要性将继续增长。' },
      ],
    },
    {
      id: 'cet6-2025-12-passage1',
      title: '六级25年12月 套1 短文 慢生活运动',
      source: '六级真题',
      level: 'B2',
      wordCount: 270,
      sentenceCount: 11,
      duration: '02:05',
      sentences: [
        { en: 'The slow living movement encourages people to intentionally slow down the pace of their lives.', cn: '慢生活运动鼓励人们有意地放慢生活节奏。' },
        { en: 'It began as a reaction to the fast-paced, always-connected nature of modern society.', cn: '它始于对现代社会快节奏、始终在线特性的一种反应。' },
        { en: 'Proponents argue that constant busyness prevents us from truly experiencing and enjoying life.', cn: '支持者认为，持续的忙碌使我们无法真正体验和享受生活。' },
        { en: 'When we rush from one task to the next, we miss the small moments that make life meaningful.', cn: '当我们从一个任务匆忙赶到下一个时，我们错过了让生活有意义的小瞬间。' },
        { en: 'Slow living involves simplifying, prioritizing what matters, and saying no to the rest.', cn: '慢生活包括简化、优先处理重要的事，对其余的说不。' },
        { en: 'It\'s not about doing everything slowly—it\'s about doing the right things at the right pace.', cn: '它不是指慢慢地做每件事——而是以合适的节奏做正确的事。' },
        { en: 'This can mean cooking meals from scratch instead of eating fast food.', cn: '这可能意味着从头开始做饭，而不是吃快餐。' },
        { en: 'It can mean taking time to savor your coffee instead of drinking it while checking emails.', cn: '它可能意味着花时间品尝咖啡，而不是一边查邮件一边喝。' },
        { en: 'Research suggests that slower, more intentional living reduces stress and improves well-being.', cn: '研究表明，更慢、更有意的生活可以减轻压力，改善幸福感。' },
        { en: 'It can also improve relationships by allowing us to be fully present with others.', cn: '它还可以通过让我们完全与他人同处当下来改善人际关系。' },
        { en: 'While slow living isn\'t for everyone, many find it a valuable antidote to modern stress.', cn: '虽然慢生活并不适合每个人，但许多人发现它是应对现代压力的有效解药。' },
      ],
    },
    {
      id: 'cet6-2026-06-conversation1',
      title: '六级26年6月 套1 长对话 职业转型',
      source: '六级真题',
      level: 'B2',
      wordCount: 260,
      sentenceCount: 13,
      duration: '02:00',
      sentences: [
        { en: 'M: I\'ve been thinking about making a career change, but I\'m not sure where to start.', cn: '男：我一直在考虑转行，但不知道从哪里开始。' },
        { en: 'I\'ve been in finance for eight years, and I\'m feeling burnt out.', cn: '我在金融行业干了八年，感觉精疲力竭了。' },
        { en: 'W: That\'s a big step. What is it you\'re looking for in a new career?', cn: '女：这是一大步。你在新职业中寻找什么？' },
        { en: 'M: I want something more meaningful. I want to feel like my work makes a positive difference.', cn: '男：我想要更有意义的工作。我想感觉到我的工作产生了积极的影响。' },
        { en: 'I\'ve always been interested in environmental issues.', cn: '我一直对环境问题感兴趣。' },
        { en: 'W: Have you considered sustainable finance or ESG investing?', cn: '女：你考虑过可持续金融或ESG投资吗？' },
        { en: 'That way, you could use your existing skills while working in a field you care about.', cn: '那样的话，你可以在你关心的领域工作的同时，利用你现有的技能。' },
        { en: 'M: I haven\'t thought about that. That could be a good middle ground.', cn: '男：我没想过这个。这可能是个很好的中间地带。' },
        { en: 'What would I need to do to make that kind of transition?', cn: '要实现这种转变，我需要做什么？' },
        { en: 'W: You could start by taking some courses in sustainable business.', cn: '女：你可以先修一些可持续商业的课程。' },
        { en: 'Networking with people in the field would also help.', cn: '与该领域的人建立联系也会有帮助。' },
        { en: 'Maybe try volunteering or doing freelance projects to gain relevant experience.', cn: '也许可以尝试志愿服务或做自由职业项目来获得相关经验。' },
        { en: 'M: That\'s solid advice. I feel more optimistic about this already.', cn: '男：这是可靠的建议。我对此已经感到更乐观了。' },
      ],
    },
    {
      id: 'cet6-2026-06-passage1',
      title: '六级26年6月 套1 短文 创造力的本质',
      source: '六级真题',
      level: 'C1',
      wordCount: 285,
      sentenceCount: 12,
      duration: '02:12',
      sentences: [
        { en: 'Creativity is often misunderstood as a rare gift possessed only by artists and geniuses.', cn: '创造力常被误解为只有艺术家和天才才拥有的罕见天赋。' },
        { en: 'But modern research suggests that creativity is a skill that anyone can develop.', cn: '但现代研究表明，创造力是一种任何人都可以发展的技能。' },
        { en: 'It\'s not about being born with special abilities—it\'s about learning to think differently.', cn: '它不是关于天生具有特殊能力——而是关于学会以不同的方式思考。' },
        { en: 'One key insight is that creative ideas are rarely completely new.', cn: '一个关键洞见是，创意很少是完全新颖的。' },
        { en: 'More often, they are novel combinations of existing ideas and concepts.', cn: '更常见的是，它们是现有想法和概念的新颖组合。' },
        { en: 'The printing press, for example, combined existing technologies like the screw press and movable type.', cn: '例如，印刷机结合了螺旋压力机和活字等现有技术。' },
        { en: 'This means that exposing yourself to diverse ideas and experiences can boost your creativity.', cn: '这意味着，接触多样化的想法和体验可以提升你的创造力。' },
        { en: 'Another important factor is giving yourself time for unfocused thinking.', cn: '另一个重要因素是给自己时间进行不专注的思考。' },
        { en: 'Our best ideas often come when we\'re not actively trying to solve a problem.', cn: '我们最好的想法往往出现在我们没有积极试图解决问题的时候。' },
        { en: 'Walking, showering, or doing other routine activities allows our minds to wander and make connections.', cn: '散步、洗澡或做其他日常活动，让我们的思维能够漫游并建立联系。' },
        { en: 'Contrary to popular belief, creativity also requires hard work and persistence.', cn: '与普遍看法相反，创造力也需要努力和坚持。' },
        { en: 'Genius is one percent inspiration and ninety-nine percent perspiration, as the saying goes.', cn: '俗话说，天才是百分之一的灵感加百分之九十九的汗水。' },
      ],
    },
    {
      id: 'cet6-2026-12-lecture1',
      title: '六级26年12月 套1 讲座 气候适应',
      source: '六级真题',
      level: 'C1',
      wordCount: 300,
      sentenceCount: 13,
      duration: '02:20',
      sentences: [
        { en: 'While reducing greenhouse gas emissions remains essential, we must also adapt to changes already underway.', cn: '虽然减少温室气体排放仍然至关重要，但我们也必须适应已经在发生的变化。' },
        { en: 'This field is known as climate adaptation, and it\'s growing in importance every year.', cn: '这个领域被称为气候适应，其重要性每年都在增长。' },
        { en: 'Climate adaptation involves adjusting our societies and infrastructure to handle new climate realities.', cn: '气候适应包括调整我们的社会和基础设施，以应对新的气候现实。' },
        { en: 'This means building flood defenses in areas facing rising sea levels and more intense storms.', cn: '这意味着在面临海平面上升和更强烈风暴的地区建造防洪设施。' },
        { en: 'It means developing drought-resistant crops for regions getting hotter and drier.', cn: '它意味着为越来越热和越来越干燥的地区开发抗旱作物。' },
        { en: 'It also means designing buildings and cities to withstand extreme heat events.', cn: '它还意味着设计能够抵御极端高温事件的建筑和城市。' },
        { en: 'Adaptation requires planning ahead and investing in resilience before disasters strike.', cn: '适应需要提前规划，在灾难发生前投资于韧性建设。' },
        { en: 'This is often more cost-effective than trying to recover after a disaster has occurred.', cn: '这通常比灾难发生后试图恢复更具成本效益。' },
        { en: 'However, adaptation also raises important questions about justice and equity.', cn: '然而，适应也引发了关于正义和公平的重要问题。' },
        { en: 'The countries most vulnerable to climate change are often those that contributed least to causing it.', cn: '最容易受气候变化影响的国家，往往是对造成气候变化贡献最小的国家。' },
        { en: 'Wealthier nations have a responsibility to help poorer countries adapt.', cn: '较富裕的国家有责任帮助较贫穷的国家适应。' },
        { en: 'As climate impacts worsen, finding fair and effective adaptation strategies will become increasingly urgent.', cn: '随着气候影响恶化，找到公平有效的适应策略将变得越来越紧迫。' },
      ],
    },
    // ---------- 考研 2025-2026 真题（高质量） ----------
    {
      id: 'kaoyan-2025-sectionA1',
      title: '考研英语一 2025年 Section A 对话 文献阅读方法',
      source: '考研真题',
      level: 'C1',
      wordCount: 290,
      sentenceCount: 14,
      duration: '02:18',
      sentences: [
        { en: 'W: Professor, I\'m drowning in papers for my literature review.', cn: '女：教授，我快被文献综述的论文淹没了。' },
        { en: 'There are hundreds of articles on my topic, and I can\'t possibly read them all.', cn: '关于我的主题有数百篇文章，我不可能全部读完。' },
        { en: 'M: That\'s a common challenge. The key is to read strategically, not comprehensively.', cn: '男：这是一个常见的挑战。关键是有策略地阅读，而不是全面阅读。' },
        { en: 'W: What do you mean by strategically?', cn: '女：你说的有策略是什么意思？' },
        { en: 'M: Start by identifying the most important papers in your field.', cn: '男：首先确定你所在领域最重要的论文。' },
        { en: 'Look for highly cited works and recent review articles that summarize the field.', cn: '找高被引的著作和总结该领域的最新综述文章。' },
        { en: 'Those will give you a good overview without having to read everything.', cn: '这些会给你一个很好的概览，而不必阅读所有内容。' },
        { en: 'W: And once I have the overview?', cn: '女：那有了概览之后呢？' },
        { en: 'M: Then you can dive deeper into specific papers that are most relevant to your research question.', cn: '男：然后你可以深入阅读与你的研究问题最相关的特定论文。' },
        { en: 'For each paper, read the abstract and conclusion first.', cn: '对于每篇论文，先读摘要和结论。' },
        { en: 'If it still seems relevant, read the introduction and skim the methodology and results.', cn: '如果仍然相关，再读引言，浏览方法和结果部分。' },
        { en: 'Only read the whole paper carefully if it\'s truly central to your work.', cn: '只有当论文真正对你的工作至关重要时，才仔细阅读全文。' },
        { en: 'W: That makes sense. I\'ve been trying to read every paper from start to finish.', cn: '女：有道理。我一直试图从头到尾读每一篇论文。' },
        { en: 'M: That would take forever. Smart reading is about knowing what to skip.', cn: '男：那永远读不完。聪明的阅读在于知道什么可以跳过。' },
      ],
    },
    {
      id: 'kaoyan-2025-sectionB1',
      title: '考研英语一 2025年 Section B 短文 自由意志之争',
      source: '考研真题',
      level: 'C1',
      wordCount: 305,
      sentenceCount: 12,
      duration: '02:25',
      sentences: [
        { en: 'The question of free will has puzzled philosophers and scientists for millennia.', cn: '自由意志的问题困扰了哲学家和科学家数千年。' },
        { en: 'Do we truly make choices freely, or are our decisions determined by prior causes?', cn: '我们真的能自由地做出选择吗，还是我们的决定由先前的原因决定？' },
        { en: 'The traditional philosophical debate pits determinism against libertarian free will.', cn: '传统的哲学辩论将决定论与自由主义自由意志对立起来。' },
        { en: 'Determinists argue that every event, including human decisions, has a sufficient cause.', cn: '决定论者认为，每一个事件，包括人类的决定，都有充分的原因。' },
        { en: 'Given the state of the universe and the laws of nature, only one future is possible.', cn: '给定宇宙的状态和自然法则，只有一种未来是可能的。' },
        { en: 'Libertarians counter that humans have a special capacity for free choice that transcends physical causation.', cn: '自由主义者反驳说，人类有一种超越物理因果的特殊自由选择能力。' },
        { en: 'Compatibilists take a middle position, arguing that free will and determinism can coexist.', cn: '兼容论者采取中间立场，认为自由意志和决定论可以共存。' },
        { en: 'They redefine free will as acting in accordance with one\'s own desires and reasons.', cn: '他们将自由意志重新定义为按照自己的欲望和理性行事。' },
        { en: 'Even if those desires are determined, the choice is still free in the sense that matters.', cn: '即使这些欲望是被决定的，选择在重要的意义上仍然是自由的。' },
        { en: 'Neuroscience has added a new dimension to the debate with experiments suggesting decisions are made unconsciously before we become aware of them.', cn: '神经科学为这场辩论增加了新的维度，实验表明，在我们意识到之前，决定就已经无意识地做出了。' },
        { en: 'While these findings are provocative, their interpretation remains controversial.', cn: '虽然这些发现很有煽动性，但它们的解释仍然存在争议。' },
        { en: 'The free will debate shows no signs of being resolved anytime soon.', cn: '自由意志的辩论没有迹象表明会很快得到解决。' },
      ],
    },
    {
      id: 'kaoyan-2025-sectionC1',
      title: '考研英语一 2025年 Section C 讲座 后真相时代',
      source: '考研真题',
      level: 'C2',
      wordCount: 325,
      sentenceCount: 13,
      duration: '02:32',
      sentences: [
        { en: 'The term "post-truth" was named Word of the Year in 2016, reflecting a growing concern about the state of public discourse.', cn: '"后真相"一词被评为2016年度词汇，反映了人们对公共话语状态日益增长的担忧。' },
        { en: 'In a post-truth world, objective facts are less influential than appeals to emotion and personal belief.', cn: '在后真相世界中，客观事实的影响力不如对情感和个人信仰的诉求。' },
        { en: 'People increasingly live in information bubbles where they encounter only views that confirm their existing beliefs.', cn: '人们越来越多地生活在信息泡沫中，在那里他们只遇到能证实自己已有信念的观点。' },
        { en: 'Social media algorithms reinforce this by showing us content we are likely to agree with.', cn: '社交媒体算法通过向我们展示我们可能同意的内容来强化这一点。' },
        { en: 'This creates echo chambers where misinformation can spread unchallenged.', cn: '这创造了回音室，错误信息可以在其中不受质疑地传播。' },
        { en: 'The consequences are profound: declining trust in institutions, polarization, and an inability to agree on basic facts.', cn: '后果是深远的：对机构的信任下降、两极分化、以及无法就基本事实达成一致。' },
        { en: 'When people can\'t agree on what\'s true, democratic deliberation becomes nearly impossible.', cn: '当人们无法就什么是真的达成一致时，民主审议变得几乎不可能。' },
        { en: 'Addressing this challenge requires action on multiple fronts.', cn: '应对这一挑战需要在多个方面采取行动。' },
        { en: 'Media literacy education can help people evaluate sources and identify misinformation.', cn: '媒体素养教育可以帮助人们评估信息来源并识别错误信息。' },
        { en: 'Platform companies need to take more responsibility for the content they amplify.', cn: '平台公司需要对它们放大的内容承担更多责任。' },
        { en: 'And we all need to cultivate intellectual humility and willingness to engage with opposing views.', cn: '我们都需要培养理智上的谦逊，以及与对立观点接触的意愿。' },
        { en: 'The health of our democracies may depend on whether we can rebuild a shared reality.', cn: '我们民主的健康可能取决于我们能否重建一个共同的现实。' },
        { en: 'This is perhaps the defining challenge of the information age.', cn: '这也许是信息时代的决定性挑战。' },
      ],
    },
    {
      id: 'kaoyan-2026-sectionA1',
      title: '考研英语一 2026年 Section A 对话 学术写作建议',
      source: '考研真题',
      level: 'C1',
      wordCount: 295,
      sentenceCount: 14,
      duration: '02:20',
      sentences: [
        { en: 'W: I got my paper back from the journal, and the reviewers said my writing is unclear.', cn: '女：我收到了期刊的退稿，审稿人说我的写作不清楚。' },
        { en: 'They want major revisions, but I\'m not sure how to improve the clarity.', cn: '他们要求重大修改，但我不知道如何提高清晰度。' },
        { en: 'M: That\'s a common issue, especially for early-career researchers.', cn: '男：这是一个常见问题，尤其是对于早期职业研究者。' },
        { en: 'Academic writing is a skill that takes practice to develop.', cn: '学术写作是一种需要练习才能发展的技能。' },
        { en: 'W: Do you have any specific suggestions?', cn: '女：你有什么具体的建议吗？' },
        { en: 'M: Start with the structure. Each paragraph should have one clear main point.', cn: '男：从结构开始。每一段应该有一个明确的要点。' },
        { en: 'State that point in the first sentence, then support it with evidence and reasoning.', cn: '在第一句中说明这个要点，然后用证据和推理来支持。' },
        { en: 'Also, pay attention to your sentence structure.', cn: '另外，注意你的句子结构。' },
        { en: 'Long, complex sentences are harder to follow. Mix in shorter sentences for clarity.', cn: '长而复杂的句子更难理解。混合使用短句以提高清晰度。' },
        { en: 'W: What about vocabulary? Should I use more technical terms?', cn: '女：词汇呢？我应该使用更多的技术术语吗？' },
        { en: 'M: Only when they\'re necessary and precise.', cn: '男：只在必要且精确的时候。' },
        { en: 'Don\'t use jargon just to sound academic—it usually has the opposite effect.', cn: '不要为了听起来学术而使用行话——通常会适得其反。' },
        { en: 'The best academic writing is clear and direct, not unnecessarily complex.', cn: '最好的学术写作是清晰直接的，而不是不必要的复杂。' },
        { en: 'W: That\'s helpful. I\'ll revise with these principles in mind.', cn: '女：很有帮助。我会牢记这些原则来修改。' },
      ],
    },
    {
      id: 'kaoyan-2026-sectionB1',
      title: '考研英语一 2026年 Section B 短文 技术失业',
      source: '考研真题',
      level: 'C2',
      wordCount: 315,
      sentenceCount: 13,
      duration: '02:30',
      sentences: [
        { en: 'The fear that technology will destroy jobs is as old as the Industrial Revolution itself.', cn: '对技术会摧毁工作的恐惧与工业革命本身一样古老。' },
        { en: 'In the 19th century, Luddites destroyed textile machines they believed would take their livelihoods.', cn: '在19世纪，勒德分子摧毁了他们认为会夺走他们生计的纺织机器。' },
        { en: 'Yet history shows that technological change ultimately creates more jobs than it destroys.', cn: '然而历史表明，技术变革最终创造的就业岗位多于它摧毁的。' },
        { en: 'While some jobs disappear, new ones emerge that we couldn\'t have imagined before.', cn: '虽然一些工作消失了，但新的工作出现了，这是我们以前无法想象的。' },
        { en: 'But this time might be different, argue some economists.', cn: '但一些经济学家认为，这次可能有所不同。' },
        { en: 'Artificial intelligence and automation threaten not just manual labor but cognitive work as well.', cn: '人工智能和自动化不仅威胁体力劳动，也威胁认知工作。' },
        { en: 'Jobs that were once considered safe from automation—law, medicine, finance—now look vulnerable.', cn: '曾经被认为不会被自动化取代的工作——法律、医学、金融——现在看起来很脆弱。' },
        { en: 'If AI can perform increasingly sophisticated cognitive tasks, what will humans do?', cn: '如果AI能执行越来越复杂的认知任务，人类将做什么？' },
        { en: 'Optimists argue that new types of work will emerge, just as they always have.', cn: '乐观主义者认为，新型工作将会出现，就像以往一样。' },
        { en: 'Pessimists worry that this time the transition will be too fast and too disruptive.', cn: '悲观主义者担心，这次转型会太快、太具破坏性。' },
        { en: 'They propose policies like universal basic income to help people through the transition.', cn: '他们提出全民基本收入等政策，帮助人们度过转型期。' },
        { en: 'Whatever the outcome, the nature of work is likely to change dramatically in the coming decades.', cn: '无论结果如何，工作的本质在未来几十年可能会发生巨大变化。' },
        { en: 'Preparing for that change is one of the great challenges of our time.', cn: '为这一变化做好准备是我们这个时代的重大挑战之一。' },
      ],
    },
    {
      id: 'kaoyan-2026-sectionC1',
      title: '考研英语一 2026年 Section C 讲座 具身认知',
      source: '考研真题',
      level: 'C2',
      wordCount: 335,
      sentenceCount: 14,
      duration: '02:38',
      sentences: [
        { en: 'For centuries, Western thought has drawn a sharp distinction between mind and body.', cn: '几个世纪以来，西方思想在心灵与身体之间划出了鲜明的界限。' },
        { en: 'The mind was seen as rational, abstract, and separate from the physical world.', cn: '心灵被视为理性的、抽象的，与物理世界分离。' },
        { en: 'The body was merely a vessel that carried the mind around.', cn: '身体仅仅是承载心灵的容器。' },
        { en: 'But a growing field called embodied cognition challenges this traditional view.', cn: '但一个名为具身认知的新兴领域挑战了这一传统观点。' },
        { en: 'Embodied cognition argues that our bodies shape our minds in profound ways.', cn: '具身认知认为，我们的身体以深刻的方式塑造着我们的心灵。' },
        { en: 'Thinking is not something that happens only in the brain—it involves the whole body interacting with the environment.', cn: '思考不是只发生在大脑中的事情——它涉及整个身体与环境的互动。' },
        { en: 'Consider how we understand abstract concepts like time.', cn: '想想我们如何理解时间这样的抽象概念。' },
        { en: 'We talk about the future being "ahead" of us and the past being "behind" us.', cn: '我们说未来在我们"前面"，过去在我们"后面"。' },
        { en: 'These spatial metaphors aren\'t just figures of speech—they reflect how we actually think about time.', cn: '这些空间隐喻不仅仅是修辞手法——它们反映了我们实际上如何思考时间。' },
        { en: 'Experiments show that people lean forward when thinking about the future and backward when thinking about the past.', cn: '实验表明，人们在思考未来时会向前倾，在思考过去时会向后倾。' },
        { en: 'Similarly, we understand warmth in terms of physical warmth and coldness.', cn: '同样，我们从身体的温暖和寒冷的角度来理解温暖。' },
        { en: 'Holding a warm cup of coffee makes people perceive others as warmer and friendlier.', cn: '拿着一杯热咖啡会让人们觉得他人更温暖、更友好。' },
        { en: 'These findings suggest that our abstract thinking is grounded in our physical experiences.', cn: '这些发现表明，我们的抽象思维植根于我们的身体体验。' },
        { en: 'The implications extend from education to artificial intelligence, fundamentally changing how we understand the mind.', cn: '其影响从教育延伸到人工智能，从根本上改变了我们对心灵的理解。' },
      ],
    },
`;

// 替换前20篇
const newContent = content.substring(0, firstBraceIdx) + newArticles + content.substring(endPos);

fs.writeFileSync(filePath, newContent, 'utf8');
console.log('✅ 成功替换前20篇为高质量真题');
console.log('新文件大小:', newContent.length, '字符');
